### ISSUE TITLE
Error parsing feed XML.

### ISSUE THREAD

**Issue by niuyaweiqq** [MarkusLewis/Podcast-Feed-Library#13]
com.icosillion.podengine.exceptions.InvalidFeedException: Error parsing feed XML.

from url: http://www.ivoox.com/feed_fg_f169818_filtro_1.html

Please see what the problem is.

**Comment by ShineYang** [comment]
Same problem. Error info:
`com.icosillion.podengine.exceptions.InvalidFeedException: Error parsing feed XML.
	at com.icosillion.podengine.models.Podcast.<init>(Podcast.java:67)
	at Main.main(Main.java:20)
Caused by: org.dom4j.DocumentException: Error on line 1 of document  :  Premature end of file
	at org.dom4j.io.SAXReader.read(SAXReader.java:466)
	at org.dom4j.DocumentHelper.parseText(DocumentHelper.java:275)
	at com.icosillion.podengine.models.Podcast.<init>(Podcast.java:58)
	... 1 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1014)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.dom4j.io.SAXReader.read(SAXReader.java:449)
	... 3 more`
