### ISSUE TITLE
Invalid feed...?

### ISSUE THREAD

**Issue by rehmke** [MarkusLewis/Podcast-Feed-Library#4]
Hello,

    I have been using this library for some time, which is excellent, though recently it seems that an InvalidFeedException is encountered using a familiar/curated feed URL, which is a 'head scratcher'.  

    I have tried to debug, though there seems to be some issue with the following URL that I am unable to track down - any thoughts?  

        - https://www.iselectfund.com/feed/podcast/

    Please advise, and thanks.

rehmke

**Comment by MarkusLewis** [comment]
Hi rehmke,

Could you post the full stack trace that you're getting?

**Comment by rehmke** [comment]
It seems that an odd SSL exception is being encountered - unrelated to the project's source code, it seems:

`com.icosillion.podengine.exceptions.InvalidFeedException: Error reading feed.
	at com.icosillion.podengine.models.Podcast.<init>(Unknown Source)
	at test.Main.main(Main.java:24)
Caused by: javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
	at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1441)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2016)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	... 2 more`

**Comment by rehmke** [comment]
As it turned out, there was an SSL change somewhere in the chain with regard to the source of the feed, resulting in some sort of error.  To correct, in my Java source, I added the following initialization configuration:

`System.setProperty("jsse.enableSNIExtension", "false");`

Thanks,

rehmke
